version: '3.6'

services:
  ### Common services
  sql-data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word

  nosql-data:
    image: mongo
      
  rabbitmq:
    image: rabbitmq:3.8.5-management-alpine
  ### / Common services