version: '3.4'

services:
  identity.api:
    image: skeleton/identity.api
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sql.data
      
  locations.api:
    image: skeleton/locations.api
    build:
      context: .
      dockerfile: Services/Locations/Locations.API/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  status.web:
    image: skeleton/status.web
    build:
      context: .
      dockerfile: WebApplications/Status.Web/Dockerfile
      
  webapi.base:
    image: skeleton/webapi.base
    build:
      context: .
      dockerfile: ApiGateways/WebAPI.Base/Dockerfile

  webspa.administration:
    image: skeleton/webspa.administration
    build:
      context: .
      dockerfile: WebApplications/WebSPA.Administration/Dockerfile    
    depends_on:
      - identity.api
      - locations.api

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3.7-management
