version: '3.6'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80      
      - SpaClient=http://localhost:5111
      - ConnectionString=${Skeleton_AZURE_IDENTITY_DB:-Server=sql.data;Database=SkeletonOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word}
      - IdentityUrlExternal=http://localhost:5101
      - LocationApiClient=http://localhost:5102
    ports:
      - "5101:80"

  locations.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5102
      - ConnectionString=${Skeleton_AZURE_COSMOSDB:-mongodb://nosql.data}
      - Database=LocationsDb
      - IdentityUrlExternal=http://10.0.75.1:5101
    ports:
      - "5102:5102"

  knowledgebase.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5103
      - ConnectionString=${Skeleton_AZURE_IDENTITY_DB:-Server=sql.data;Database=SkeletonOnContainers.Services.KnowledgeBaseDb;User Id=sa;Password=Pass@word}
      - Database=LocationsDb
      - IdentityUrlExternal=http://10.0.75.1:5101
    ports:
      - "5103:5103"

  status.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://identity.api/hc
      - LocationsUrl=http://locations.api/hc
      - KnowledgeBaseUrl=http://knowledgebase.api/hc
      - AdministrationSPAUrl=http://webspa.administration
    ports:
      - "5110:80"
      
  webapi.base:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api
    ports:
      - "5200:80"
    volumes:
      - ./ApiGateways/WebSPA.Administration/apigw:/app/configuration

  webspa.administration:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5111:80"

  sql.data:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "5433:1433"
      
  nosql.data:
    ports:
      - "27017:27017"

  elasticsearch.data:
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    ports:
      - "5601:5601"

  rabbitmq:
    ports:
      - "15672:15672"  # Important: Remove on production environment
      - "5672:5672"    # Important: Remove on production environment
